/**
 * Writes dist/sw.js after a build.
 *
 *   node tools/build-sw.ts
 *
 * Vite hashes asset filenames, so the precache list has to be produced from
 * the actual build output rather than hand-maintained. The cache name is
 * derived from the file list, so a changed build invalidates the old cache.
 */
import { createHash } from 'node:crypto';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, posix, relative, sep } from 'node:path';

const dist = join(process.cwd(), 'dist');

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const all = walk(dist).map((f) => relative(dist, f).split(sep).join(posix.sep));

/** Everything needed to open the app and play: markup, code, styles, icons. */
const shell = all.filter((f) => f !== 'sw.js');

const fingerprint = createHash('sha256')
  .update(shell.map((f) => `${f}:${statSync(join(dist, f)).size}`).join('\n'))
  .digest('hex')
  .slice(0, 12);

const sw = `/* Generated by tools/build-sw.ts — do not edit. */
const VERSION = ${JSON.stringify(fingerprint)};
const SHELL_CACHE = 'sv-shell-' + VERSION;

const SHELL = ${JSON.stringify(['./', ...shell], null, 2)};

/*
 * ignoreVary matters more than it looks. Static hosts commonly send
 * "Vary: Origin". addAll() stores those responses against no-cors requests
 * that carry no Origin header, but the browser asks for module scripts and
 * stylesheets in CORS mode *with* one — so Vary matching rejects the entry,
 * the lookup misses, and offline loads fall through to a dead network. It
 * only shows up once actually offline: a same-origin fetch() sends no Origin
 * header and matches perfectly, which makes it look fine right up until it
 * isn't.
 */
const MATCH = { ignoreVary: true };

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(SHELL_CACHE)
      .then((cache) => cache.addAll(SHELL))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== SHELL_CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations fall back to the cached shell so the app opens offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches
          .match('./', MATCH)
          .then((hit) => hit || caches.match('./index.html', MATCH)),
      ),
    );
    return;
  }

  // Everything else is a hashed build asset: cache first, network as backup.
  event.respondWith(caches.match(request, MATCH).then((hit) => hit || fetch(request)));
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
const shellBytes = shell.reduce((t, f) => t + statSync(join(dist, f)).size, 0);
console.log(
  `sw.js  version ${fingerprint}\n` +
    `  precached shell   ${shell.length} files, ${(shellBytes / 1024).toFixed(0)} kB`,
);
